service: aws-nodejs-typescript-s3

plugins:
  - serverless-esbuild
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  stage: ${opt:stage, 'dev'}
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
  environment: ${file(./src/config/env.${opt:stage, 'dev'}.yml)}

functions:
  receiver:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
      

package: 
  individually: true
custom:
  esbuild:

    bundle: true
    minify: false
    watch:
      pattern: ['src/**/*.ts']
